---
version: "3"
services:
    syncthing:
        image: "linuxserver/syncthing:latest"
        container_name: "Syncthing"
        network_mode: host
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/London
        volumes:
            - /sharedfolders/Syncthing:/sync
            - /sharedfolders/Config/syncthing:/config
            - /sharedfolders/Media:/sync/Media
            - /sharedfolders/Documents:/sync/Documents
        restart: unless-stopped
