---
version: "3"
services:
    plex:
        image: linuxserver/plex:latest
        container_name: Plex
        network_mode: host
        environment:
            - PUID=1000
            - PGID=100
            - VERSION=docker
        volumes:
            - /srv/dev-disk-by-label-HDD/Media:/media
            - /srv/dev-disk-by-label-HDD/Config/plex:/config
        restart: unless-stopped
