---
version: "3"
services:
    plex:
        image: linuxserver/plex:latest
        container_name: Plex
        network_mode: host
        environment:
            - PUID=1000
            - PGID=100
            - VERSION=docker
        volumes:
            - /sharedfolders/Media:/media
            - /sharedfolders/Config/plex:/config
            - /sharedfolders/Transcode:/transcode
        restart: unless-stopped
